### ISSUE TITLE
Transferring CBOR

### ISSUE THREAD

**Issue by tomciopp** [masonforest/elixir-cbor#4]
Hey!

We forked excbor and are looking to become the canonical CBOR encoding/decoding library for elixir. I see that you are looking to transfer the hex package to a new maintainer and was hoping that we could take it over.

Please review the code and feel free to ask any questions. All of the tests which are referenced from the Appendix of the RFC are passing, and it should be fairly easy to extend if you need to do custom work in any codebase.

**Comment by tomciopp** [comment]
I probably should provide a link 

https://github.com/scalpel-software/cbor

**Comment by tomciopp** [comment]
@masonforest Hey, it's been two weeks. Have you had the time to look at this?

**Comment by masonforest** [comment]
Hey! Sorry I wasn't "watching" this repo on GitHub. Yeah, I'd be happy to get this transferred over!

shoot me an email (mason@kissr.co) or hit me up on Telegram (@masonforest )

One question I had: is it possible to encode and decode a "Byte String" and a "Text String" with your implementation?

In my implementation I'm treating atoms as text string and binaries and bytes strings.

Looking forward to chatting more.

Thanks!

-Mason

**Comment by tomciopp** [comment]
@masonforest My version is an update and extension of `excbor` so it follows the same rules. It will return a CBOR.Tag of the following form: `%CBOR.Tag{tag: :bytes, value: <<1,2,3>>}` 

I treat atoms as text except for `true` `false` `nil` and `__undefined__`. 

I also implemented several other data structures. Since cbor does not have a specification for ranges, sets, tuples, or keyword lists, I treat data of that type as lists. I also implemented encoding and decoding for `Time`, `NaiveDateTime`, `DateTime`, `Date` and `URI`. Since encoding is a protocol, you can also encode additional custom data types.

I'll send you an email, I may need some help writing docs to help those who are using your version update to mine.
